- name: Frontend setup
  hosts: frontend
  become: true
  vars:
    backend_ip: "{{ hostvars['u21.local']['ansible_host'] }}"
  tasks:
    - name: Enable nginx1 via amazon-linux-extras on Amazon Linux 2
      command: amazon-linux-extras enable nginx1
      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

    - name: Install nginx on Amazon Linux 2 using yum
      command: yum install -y nginx
      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

    - name: Install nginx on Debian family (like Ubuntu)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Copy nginx reverse proxy config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: restart nginx
