---
- name: Gather facts for all nodes
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

- name: Frontend setup
  hosts: frontend
  roles:
    - frontend

- name: Backend setup
  hosts: backend
  roles:
    - backend
