---
- name: Install required packages
  apt:
    name:
      - curl
      - netdata
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Ensure Netdata is started and enabled
  service:
    name: netdata
    state: started
    enabled: yes
